/**
 * Bearing gold case catalog (hybrid screening_reference + pending vendor gold).
 * Expected values are filled by `scripts/seed-bearings-gold.ts` or refreshed
 * when running vitest with UPDATE_BEARINGS_GOLD=1.
 */

import type { BearingsGoldCase } from "./bearingsGold";

/** Input-only seeds; screening expects are snapshot at test/run time. */
export const BEARINGS_GOLD_SEEDS: Array<
  Omit<BearingsGoldCase, "expect" | "tolerancePct"> & {
    expect?: BearingsGoldCase["expect"];
    tolerancePct?: number;
  }
> = [
  {
    id: "gold-6205-iso281-baseline",
    source: "PhyCalcPro screening regression / ISO 281 form (Shigley-style duty)",
    kind: "screening_reference",
    status: "active",
    inputs: {
      radialLoad: 3000,
      axialLoad: 500,
      speed: 1500,
      lifeHours: 20000,
      safetyFactor: 1.5,
      bearingType: "deep_groove",
      designation: "6205",
      lubricantType: "oil",
      isoVgGrade: 68,
      operatingTempC: 70,
      contamination: "normal_clean",
      reliabilityPercent: 90,
    },
  },
  {
    id: "gold-6208-radial",
    source: "PhyCalcPro screening regression",
    kind: "screening_reference",
    status: "active",
    inputs: {
      radialLoad: 5000,
      axialLoad: 0,
      speed: 1800,
      lifeHours: 30000,
      safetyFactor: 1.5,
      bearingType: "deep_groove",
      designation: "6208",
      lubricantType: "oil",
      isoVgGrade: 68,
      operatingTempC: 70,
      contamination: "normal_clean",
    },
  },
  {
    id: "gold-6305-combined",
    source: "PhyCalcPro screening regression",
    kind: "screening_reference",
    status: "active",
    inputs: {
      radialLoad: 4000,
      axialLoad: 1200,
      speed: 1200,
      lifeHours: 20000,
      safetyFactor: 1.5,
      bearingType: "deep_groove",
      designation: "6305",
      lubricantType: "oil",
      isoVgGrade: 68,
      operatingTempC: 70,
      contamination: "normal_clean",
    },
  },
  {
    id: "gold-nu210-float",
    source: "PhyCalcPro screening regression",
    kind: "screening_reference",
    status: "active",
    inputs: {
      radialLoad: 8000,
      axialLoad: 0,
      speed: 1500,
      lifeHours: 40000,
      safetyFactor: 1.5,
      bearingType: "cylindrical_roller",
      designation: "NU210",
      lubricantType: "oil",
      isoVgGrade: 68,
      operatingTempC: 70,
      contamination: "normal_clean",
    },
  },
  {
    id: "gold-30208-taper",
    source: "PhyCalcPro screening regression",
    kind: "screening_reference",
    status: "active",
    inputs: {
      radialLoad: 6000,
      axialLoad: 2500,
      speed: 1000,
      lifeHours: 25000,
      safetyFactor: 1.5,
      bearingType: "tapered_roller",
      designation: "30208",
      lubricantType: "oil",
      isoVgGrade: 68,
      operatingTempC: 70,
      contamination: "normal_clean",
    },
  },
  {
    id: "gold-22210-spherical",
    source: "PhyCalcPro screening regression",
    kind: "screening_reference",
    status: "active",
    inputs: {
      radialLoad: 15000,
      axialLoad: 3000,
      speed: 800,
      lifeHours: 50000,
      safetyFactor: 1.5,
      bearingType: "spherical_roller",
      designation: "22210",
      lubricantType: "oil",
      isoVgGrade: 68,
      operatingTempC: 70,
      contamination: "normal_clean",
    },
  },
  {
    id: "gold-6205-high-contam",
    source: "PhyCalcPro screening regression — heavy contamination eC",
    kind: "screening_reference",
    status: "active",
    inputs: {
      radialLoad: 3000,
      axialLoad: 500,
      speed: 1500,
      lifeHours: 20000,
      safetyFactor: 1.5,
      bearingType: "deep_groove",
      designation: "6205",
      lubricantType: "oil",
      isoVgGrade: 68,
      operatingTempC: 70,
      contamination: "heavy_contamination",
    },
  },
  {
    id: "gold-6206-grease",
    source: "PhyCalcPro screening regression — grease path",
    kind: "screening_reference",
    status: "active",
    inputs: {
      radialLoad: 3500,
      axialLoad: 400,
      speed: 2000,
      lifeHours: 15000,
      safetyFactor: 1.5,
      bearingType: "deep_groove",
      designation: "6206",
      lubricantType: "grease",
      isoVgGrade: 68,
      operatingTempC: 70,
      contamination: "normal_clean",
    },
  },
  {
    id: "gold-nj208-locate",
    source: "PhyCalcPro screening regression",
    kind: "screening_reference",
    status: "active",
    inputs: {
      radialLoad: 7000,
      axialLoad: 500,
      speed: 1600,
      lifeHours: 30000,
      safetyFactor: 1.5,
      bearingType: "cylindrical_nj",
      designation: "NJ208",
      lubricantType: "oil",
      isoVgGrade: 68,
      operatingTempC: 70,
      contamination: "normal_clean",
    },
  },
  {
    id: "gold-6005-light",
    source: "PhyCalcPro screening regression",
    kind: "screening_reference",
    status: "active",
    inputs: {
      radialLoad: 1500,
      axialLoad: 200,
      speed: 3000,
      lifeHours: 20000,
      safetyFactor: 1.5,
      bearingType: "deep_groove",
      designation: "6005",
      lubricantType: "oil",
      isoVgGrade: 68,
      operatingTempC: 70,
      contamination: "normal_clean",
    },
  },
  {
    id: "gold-6205-override-c",
    source: "PhyCalcPro screening regression — user ratings override",
    kind: "screening_reference",
    status: "active",
    inputs: {
      radialLoad: 3000,
      axialLoad: 500,
      speed: 1500,
      lifeHours: 20000,
      safetyFactor: 1.5,
      bearingType: "deep_groove",
      designation: "6205",
      lubricantType: "oil",
      isoVgGrade: 68,
      operatingTempC: 70,
      contamination: "normal_clean",
      ratingsOverride: {
        enabled: true,
        dynamicLoadRatingN: 20000,
        staticLoadRatingN: 10000,
        fatigueLoadLimitN: 400,
      },
    },
  },
  {
    id: "gold-6205-vendor-skf-pending",
    source: "Paste SKF Product Select Lnm / P / s0 / aSKF into expect and set status active",
    kind: "vendor_skf",
    status: "pending_vendor_gold",
    inputs: {
      radialLoad: 3000,
      axialLoad: 500,
      speed: 1500,
      lifeHours: 20000,
      designation: "6205",
      lubricantType: "oil",
      isoVgGrade: 68,
      operatingTempC: 70,
      contamination: "normal_clean",
    },
    expect: { modifiedLife: 0 },
  },
  {
    id: "gold-30208-vendor-mitcalc-pending",
    source: "Paste MITCalc Lnm / P / s0 into expect and set status active",
    kind: "vendor_mitcalc",
    status: "pending_vendor_gold",
    inputs: {
      radialLoad: 6000,
      axialLoad: 2500,
      speed: 1000,
      lifeHours: 25000,
      designation: "30208",
      lubricantType: "oil",
      isoVgGrade: 68,
      operatingTempC: 70,
      contamination: "normal_clean",
    },
    expect: { modifiedLife: 0 },
  },
];
