/**
 * Seed cases for bootstrapping verification JSON files.
 * Run: npx tsx scripts/bootstrap-verification.ts
 */

export type VerificationSeed = {
  id: string;
  moduleId: string;
  description: string;
  inputs: Record<string, unknown>;
  /** Result fields to capture as expected values */
  fields: string[];
  tolerancePercent?: number;
  source?: string;
};

export const VERIFICATION_SEEDS: VerificationSeed[] = [
  {
    id: "impact-indicative-01",
    moduleId: "impact",
    description: "Impact load — 50 kg, 2 m/s delta-v, 10 ms duration",
    inputs: { mass: 50, velocityChange: 2, impactDuration: 10, crossSectionArea: 500, yieldStrength: 250 },
    fields: ["impulse", "averageForce", "safetyFactor"],
    tolerancePercent: 5,
    source: "Impulse-momentum screening",
  },
  {
    id: "corrosion-indicative-01",
    moduleId: "corrosion",
    description: "Corrosion allowance — 0.1 mm/yr, 20 yr life, 10 mm plate",
    inputs: { corrosionRate: 0.0001, designLife: 20, initialThickness: 0.01, safetyMargin: 20 },
    fields: ["corrosionAllowance", "requiredThickness"],
    tolerancePercent: 5,
    source: "Corrosion allowance = rate × life",
  },
  {
    id: "rotation-indicative-01",
    moduleId: "rotation",
    description: "Rotating mass — 10 kg, 0.2 m radius, 1500 rpm, 5 kW",
    inputs: { mass: 10, radius: 0.2, speedRPM: 1500, power: 5000 },
    fields: ["inertia", "kineticEnergy", "torque"],
    tolerancePercent: 5,
    source: "E = ½Iω², T = P/ω",
  },
  {
    id: "suspension-indicative-01",
    moduleId: "suspension",
    description: "Roll screening — 1200 kg sprung mass, 0.4g lateral",
    inputs: {
      sprungMass: 1200,
      lateralAcceleration: 3.92,
      wheelbase: 2.7,
      trackWidth: 1.6,
      cgHeight: 0.55,
      rollStiffness: 45000,
    },
    fields: ["lateralForce", "rollAngleDegrees", "loadTransfer"],
    tolerancePercent: 5,
    source: "Roll moment / roll stiffness",
  },
  {
    id: "rivets-indicative-01",
    moduleId: "rivets",
    description: "Single rivet shear — 6 mm, 2 kN shear",
    inputs: {
      rivetDiameter: 6,
      plateThickness: 3,
      quantity: 1,
      shearForce: 2000,
      axialForce: 0,
      rivetType: "solid",
      material: { name: "steel", yieldStress: 280e6, shearStrength: 170e6, bearingStrength: 340e6 },
    },
    fields: ["safetyFactorOverall", "safetyFactorShear"],
    tolerancePercent: 5,
    source: "Rivet shear/bearing screening",
  },
  {
    id: "welds-indicative-01",
    moduleId: "welds",
    description: "Fillet weld — 6 mm leg, 100 mm length, 10 kN",
    inputs: {
      legSize: 6,
      weldLength: 100,
      force: 10000,
      weldType: "fillet",
      electrodeStrength: 490,
    },
    fields: ["safetyFactor", "throatStress"],
    tolerancePercent: 8,
    source: "Fillet weld throat stress",
  },
  {
    id: "beams-indicative-01",
    moduleId: "beams",
    description: "Simply supported beam — center point load",
    inputs: {
      length: 4,
      E: 210e9,
      I: 8e-5,
      c: 0.15,
      support: "simply_supported",
      meshSegments: 20,
      loads: [{ position: 2, magnitude: 10000, type: "point" }],
    },
    fields: ["maxMoment", "maxDeflection"],
    tolerancePercent: 5,
    source: "Beam FEM vs analytical",
  },
  {
    id: "roller-chains-indicative-01",
    moduleId: "roller-chains",
    description: "Roller chain drive — 5 kW, 19/38 teeth, 12.7 mm pitch",
    inputs: {
      power: 5000,
      speedDriver: 900,
      teethDriver: 19,
      teethDriven: 38,
      pitch: 0.0127,
      strands: 1,
      serviceFactor: 1.2,
    },
    fields: ["chainTension", "powerUtilization", "ratio"],
    tolerancePercent: 8,
    source: "Chain power rating screening",
  },
  {
    id: "worm-gears-indicative-01",
    moduleId: "worm-gears",
    description: "Worm gear set — 2 kW @ 1450 rpm, 1:40",
    inputs: {
      power: 2000,
      speed: 1450,
      wormStarts: 1,
      gearTeeth: 40,
      module: 0.002,
      faceWidth: 0.03,
      frictionCoeff: 0.05,
      leadAngleDeg: 5,
      yieldStress: 250e6,
    },
    fields: ["wormTorque", "efficiency", "ratio"],
    tolerancePercent: 8,
    source: "Worm gear torque relations",
  },
  {
    id: "plain-bearings-indicative-01",
    moduleId: "plain-bearings",
    description: "Journal bearing — 50 mm dia, 20 kN radial (legacy seed id)",
    inputs: {
      bearingType: "journal",
      load: 20000,
      speed: 1200,
      diameter: 0.05,
      length: 0.04,
      clearance: 0.00005,
      viscosity: 0.03,
    },
    fields: ["sommerfeldNumber", "eccentricityRatio", "minFilmThickness"],
    tolerancePercent: 3,
    source: "Sommerfeld journal bearing screening",
  },
  {
    id: "bearings-indicative-needle-01",
    moduleId: "bearings",
    description: "Needle roller — compact radial, speed margin screening",
    inputs: {
      radialLoad: 4000,
      axialLoad: 0,
      speed: 1000,
      lifeHours: 15000,
      safetyFactor: 1.5,
      bearingType: "needle_roller",
      limitingSpeedRpm: 8000,
      material: {
        name: "Steel",
        dynamicRatingFactor: 22500,
        staticRatingFactor: 32000,
        allowableLife: 1000000,
      },
    },
    fields: ["equivalentLoad", "requiredDynamicRating", "staticSafetyFactor", "speedMargin"],
    tolerancePercent: 2,
    source: "PhyCalcPro regression — needle roller",
  },
  {
    id: "bearings-indicative-self-aligning-01",
    moduleId: "bearings",
    description: "Self-aligning ball — combined Fr/Fa screening",
    inputs: {
      radialLoad: 3500,
      axialLoad: 800,
      speed: 2000,
      lifeHours: 20000,
      safetyFactor: 1.5,
      bearingType: "self_aligning_ball",
      material: {
        name: "Steel",
        dynamicRatingFactor: 14300,
        staticRatingFactor: 4000,
        allowableLife: 1000000,
      },
    },
    fields: ["equivalentLoad", "requiredDynamicRating", "staticSafetyFactor"],
    tolerancePercent: 2,
    source: "PhyCalcPro regression — self-aligning ball",
  },
  {
    id: "bearings-indicative-speed-01",
    moduleId: "bearings",
    description: "Deep groove high speed — n_lim/n margin",
    inputs: {
      radialLoad: 2000,
      axialLoad: 0,
      speed: 8000,
      lifeHours: 10000,
      safetyFactor: 1.5,
      bearingType: "deep_groove",
      limitingSpeedRpm: 20000,
      material: {
        name: "Steel",
        dynamicRatingFactor: 14800,
        staticRatingFactor: 7800,
        allowableLife: 1000000,
      },
    },
    fields: ["equivalentLoad", "requiredDynamicRating", "staticSafetyFactor", "speedMargin"],
    tolerancePercent: 2,
    source: "PhyCalcPro regression — speed margin",
  },
  {
    id: "bearings-indicative-duplex-01",
    moduleId: "bearings",
    description: "Angular contact back-to-back (O) duplex screening",
    inputs: {
      radialLoad: 5000,
      axialLoad: 3000,
      speed: 2500,
      lifeHours: 15000,
      safetyFactor: 1.5,
      bearingType: "angular_contact",
      arrangement: "back_to_back",
      material: {
        name: "Steel",
        dynamicRatingFactor: 16800,
        staticRatingFactor: 9800,
        allowableLife: 1000000,
      },
    },
    fields: ["equivalentLoad", "requiredDynamicRating", "staticSafetyFactor"],
    tolerancePercent: 2,
    source: "PhyCalcPro regression — duplex O",
  },
  {
    id: "bearings-indicative-static-01",
    moduleId: "bearings",
    description: "Deep groove high static load — s0 screening",
    inputs: {
      radialLoad: 15000,
      axialLoad: 2000,
      speed: 500,
      lifeHours: 5000,
      safetyFactor: 1.5,
      bearingType: "deep_groove",
      material: {
        name: "Steel",
        dynamicRatingFactor: 14800,
        staticRatingFactor: 7800,
        allowableLife: 1000000,
      },
    },
    fields: ["equivalentLoad", "requiredDynamicRating", "staticSafetyFactor"],
    tolerancePercent: 2,
    source: "PhyCalcPro regression — static s0",
  },
  {
    id: "shells-indicative-01",
    moduleId: "shells",
    description: "Closed thin cylinder — 0.5 MPa internal pressure",
    inputs: {
      radius: 0.5,
      thickness: 0.01,
      length: 2,
      internalPressure: 500000,
      axialForce: 0,
      bendingMoment: 0,
      modulus: 210e9,
      poisson: 0.3,
      endCondition: "closed",
      allowableStress: 170e6,
    },
    fields: ["hoopStress", "vonMisesStress", "safetyFactor"],
    tolerancePercent: 2,
    source: "Thin-shell membrane screening",
  },
  {
    id: "internal-gears-rack-indicative-01",
    moduleId: "internal-gears-rack",
    description: "Internal spur pair — 15 kW @ 1200 rpm",
    inputs: {
      gearType: "internal",
      power: 15000,
      speed: 1200,
      module: 0.003,
      pinionTeeth: 20,
      gearTeeth: 80,
      faceWidth: 0.025,
      material: { name: "Steel", E: 210e9, yieldStress: 250e6, poisson: 0.3 },
    },
    fields: ["actualRatio", "safetyFactor", "tangentialForce"],
    tolerancePercent: 2,
    source: "Internal gear Lewis screening",
  },
  {
    id: "power-screws-indicative-01",
    moduleId: "power-screws",
    description: "Square-thread power screw — 10 kN axial",
    inputs: {
      screwType: "power_screw",
      threadType: "square",
      majorDiameter: 0.05,
      pitch: 0.01,
      lead: 0.01,
      length: 0.5,
      axialForce: 10000,
      frictionCoefficient: 0.15,
      starts: 1,
    },
    fields: ["efficiency", "safetyFactor", "torque"],
    tolerancePercent: 2,
    source: "Power screw torque and efficiency",
  },
  {
    id: "tolerance-indicative-3d-01",
    moduleId: "tolerance",
    description: "3D dimensional chain worst-case and RSS magnitudes",
    inputs: {
      tolerances: [0.05, 0.02, 0.01],
      tolerancesY: [0.03, 0.01],
      tolerancesZ: [0.02],
      monteCarloSamples: 0,
    },
    fields: ["worstCase", "worstCase3d", "rss3d"],
    tolerancePercent: 1,
    source: "3D vector stack magnitudes",
  },
  {
    id: "vibrations-indicative-01",
    moduleId: "vibrations",
    description: "SDOF natural frequency — 100 kg, 50 kN/m",
    inputs: { mass: 100, stiffness: 50000, dampingRatio: 0.05, forceAmplitude: 500 },
    fields: ["naturalFrequency", "dampedFrequency"],
    tolerancePercent: 5,
    source: "fn = (1/2π)√(k/m)",
  },
  {
    id: "vessels-indicative-01",
    moduleId: "vessels",
    description: "Thin cylinder — 1 MPa, 500 mm dia, 10 mm wall",
    inputs: { pressure: 1e6, diameter: 0.5, thickness: 0.01, allowableStress: 138e6, jointEfficiency: 0.85 },
    fields: ["hoopStress", "safetyFactor"],
    tolerancePercent: 5,
    source: "Thin-wall hoop stress",
  },
  {
    id: "hydraulics-indicative-01",
    moduleId: "hydraulics",
    description: "Hydraulic cylinder — 20 MPa, 50 mm bore",
    inputs: { pressure: 20e6, boreDiameter: 0.05, rodDiameter: 0.028, stroke: 0.3 },
    fields: ["extendForce", "retractForce"],
    tolerancePercent: 5,
    source: "F = P·A",
  },
  {
    id: "vacuum-engineering-indicative-01",
    moduleId: "vacuum-engineering",
    description: "Vacuum pump sizing — default field values",
    inputs: {},
    fields: ["pumpDownTime", "conductance", "throughput"],
    tolerancePercent: 10,
    source: "Advanced systems calculator defaults",
  },
  {
    id: "plates-indicative-01",
    moduleId: "plates",
    description: "Clamped rectangular plate — uniform pressure",
    inputs: {
      length: 2,
      width: 1.2,
      thickness: 0.015,
      E: 210e9,
      nu: 0.3,
      q: 10000,
      elementsX: 8,
      elementsY: 8,
      boundaryType: "clamped",
    },
    fields: ["maxDeflection", "maxMoment"],
    tolerancePercent: 5,
    source: "Plate FEM vs Roark screening",
  },
  {
    id: "multi-pulley-indicative-01",
    moduleId: "multi-pulley",
    description: "Two-pulley open belt layout",
    inputs: { diameters: [0.2, 0.3], centerDistances: [0.5], driveType: "open" },
    fields: ["totalBeltLength", "minWrapAngle", "pulleyCount"],
    tolerancePercent: 5,
    source: "Multi-pulley geometry",
  },
  {
    id: "cams-indicative-01",
    moduleId: "cams",
    description: "Simple harmonic cam — 20 mm lift",
    inputs: {
      lift: 0.02,
      baseCircle: 0.04,
      radius: 0.01,
      speed: 1200,
      dwellAngle: 90,
      motionLaw: "simple_harmonic",
      profileType: "flat_follower",
    },
    fields: ["peakVelocity", "peakAcceleration", "peakPressureAngle"],
    tolerancePercent: 5,
    source: "Polynomial cam kinematics",
  },
  {
    id: "flywheels-indicative-01",
    moduleId: "flywheels",
    description: "Solid disk flywheel — 1 m OD, 1800 rpm",
    inputs: {
      outerDiameter: 1,
      thickness: 0.1,
      faceWidth: 0.2,
      density: 7850,
      rpm: 1800,
      yieldStress: 250e6,
    },
    fields: ["mass", "inertia", "storedEnergy"],
    tolerancePercent: 5,
    source: "E = ½Iω²",
  },
  {
    id: "planetary-gears-indicative-01",
    moduleId: "planetary-gears",
    description: "Planetary set — sun 20, planet 30, target 5:1",
    inputs: { sunTeeth: 20, planetTeeth: 30, targetRatio: 5, module: 0.003, power: 1000, speed: 1500 },
    fields: ["actualRatio", "ringTeeth", "planetCount"],
    tolerancePercent: 5,
    source: "Willis planetary ratio",
  },
  {
    id: "gear-ratio-design-indicative-01",
    moduleId: "gear-ratio-design",
    description: "Target 3:1 spur pair tooth search",
    inputs: { targetRatio: 3, maxTeeth: 100, minPinionTeeth: 17 },
    fields: ["actualRatio", "pinionTeeth", "gearTeeth"],
    tolerancePercent: 2,
    source: "Tooth-count ratio search",
  },
  {
    id: "brakes-clutches-indicative-01",
    moduleId: "brakes-clutches",
    description: "Disc brake — μ=0.3, 2 kN clamp",
    inputs: {
      frictionCoeff: 0.3,
      outerRadius: 0.15,
      innerRadius: 0.08,
      actuationForce: 2000,
      speed: 1500,
      engagementTime: 0.5,
      safetyFactorTarget: 2,
    },
    fields: ["frictionTorque", "powerDissipated", "safetyFactor"],
    tolerancePercent: 5,
    source: "Friction torque capacity",
  },
  {
    id: "shaft-hubs-indicative-01",
    moduleId: "shaft-hubs",
    description: "Interference fit hub — 50 mm shaft",
    inputs: {
      shaftDiameter: 0.05,
      hubOuterDiameter: 0.1,
      hubLength: 0.05,
      interference: 0.0001,
      frictionCoeff: 0.15,
      modulus: 210e9,
    },
    fields: ["contactPressure", "frictionTorque"],
    tolerancePercent: 5,
    source: "Lamé interference pressure",
  },
  {
    id: "pins-indicative-01",
    moduleId: "pins",
    description: "Double shear pin — 20 mm, 5 kN",
    inputs: { force: 5000, pinDiameter: 0.02, plateThickness: 0.01, pinMaterialYield: 250e6, pinCount: 2 },
    fields: ["shearStress", "shearSafety", "bearingSafety"],
    tolerancePercent: 5,
    source: "Pin shear/bearing screening",
  },
  {
    id: "sections-indicative-01",
    moduleId: "sections",
    description: "Rectangle section — 100×200 mm",
    inputs: { shape: "rectangle", width: 0.1, height: 0.2 },
    fields: ["area", "Ixx", "Iyy"],
    tolerancePercent: 2,
    source: "Section property formulas",
  },
  {
    id: "rolled-sections-indicative-01",
    moduleId: "rolled-sections",
    description: "AISC W310×97 lookup",
    inputs: { designation: "W310x97" },
    fields: ["area", "ix", "sx"],
    tolerancePercent: 2,
    source: "Rolled section catalog",
  },
  {
    id: "profiles-indicative-01",
    moduleId: "profiles",
    description: "Rectangle profile — 100×200 mm",
    inputs: { shape: { shape: "rectangle", rectangle: { width: 0.1, height: 0.2 } } },
    fields: ["area", "ixx", "iyy"],
    tolerancePercent: 2,
    source: "Profile area properties",
  },
  {
    id: "composites-indicative-01",
    moduleId: "composites",
    description: "UD lamina rule-of-mixtures — 60% fiber",
    inputs: {
      fiberVolumeFraction: 0.6,
      fiberModulus: 230e9,
      matrixModulus: 3.5e9,
      fiberStrength: 3500e6,
      matrixStrength: 80e6,
      fiberDensity: 1800,
      matrixDensity: 1200,
      fiberPoisson: 0.2,
      matrixPoisson: 0.35,
    },
    fields: ["E_longitudinal", "E_transverse", "density"],
    tolerancePercent: 5,
    source: "ROM composite stiffness",
  },
  {
    id: "temperature-properties-indicative-01",
    moduleId: "temperature-properties",
    description: "Steel derating at 200 °C",
    inputs: {
      baseYield: 250e6,
      baseModulus: 210e9,
      coefficientThermalExpansion: 12e-6,
      temperature: 200,
    },
    fields: ["adjustedYield", "adjustedModulus", "expansionPerMeter"],
    tolerancePercent: 5,
    source: "Temperature property derating",
  },
  {
    id: "heat-exchangers-indicative-01",
    moduleId: "heat-exchangers",
    description: "Counterflow HX — LMTD screening",
    inputs: {
      hotFlowRate: 1.2,
      coldFlowRate: 1.5,
      hotCp: 4180,
      coldCp: 4180,
      hotInletTemp: 150,
      coldInletTemp: 25,
      hotOutletTemp: 80,
      U: 500,
      area: 30,
      flowType: "counterflow",
    },
    fields: ["heatTransferRate", "LMTD", "effectiveness"],
    tolerancePercent: 5,
    source: "LMTD / NTU screening",
  },
  {
    id: "fits-indicative-01",
    moduleId: "fits",
    description: "ISO 50 H7/g6 fit",
    inputs: {
      nominalSize: 0.05,
      holeUpper: 0,
      holeLower: 0,
      shaftUpper: 0,
      shaftLower: 0,
      isoHoleGrade: 7,
      isoHoleLetter: "H",
      isoShaftGrade: 6,
      isoShaftLetter: "g",
    },
    fields: ["clearanceMin", "clearanceMax"],
    tolerancePercent: 2,
    source: "ISO 286 fit limits",
  },
  {
    id: "cost-estimator-indicative-01",
    moduleId: "cost-estimator",
    description: "Machined part cost screening",
    inputs: {
      materialVolume: 0.001,
      materialDensity: 7850,
      materialCostPerKg: 2.5,
      machiningTime: 2,
      machineRate: 80,
      laborTime: 1,
      laborRate: 45,
      finishPercent: 10,
      overheadPercent: 15,
      scrapPercent: 5,
    },
    fields: ["totalCost", "materialCost", "materialMass"],
    tolerancePercent: 5,
    source: "Order-of-magnitude cost model",
  },
  {
    id: "cam-toolpaths-indicative-01",
    moduleId: "cam-toolpaths",
    description: "End mill pocket — 10 mm tool",
    inputs: {
      toolDiameter: 10,
      numFlutes: 4,
      spindleSpeed: 8000,
      feedPerTooth: 0.05,
      axialDepth: 2,
      radialDepth: 5,
      stockLength: 100,
      stockWidth: 50,
      stepOverPercent: 40,
    },
    fields: ["feedRate", "surfaceSpeed", "totalCutTime"],
    tolerancePercent: 5,
    source: "CAM MRR screening",
  },
  {
    id: "cryogenic-engineering-indicative-01",
    moduleId: "cryogenic-engineering",
    description: "Cryogenic heat leak — defaults",
    inputs: {},
    fields: ["totalHeatLeak", "boiloffRate"],
    tolerancePercent: 10,
    source: "Advanced systems calculator defaults",
  },
  {
    id: "magnetic-fields-indicative-01",
    moduleId: "magnetic-fields",
    description: "Solenoid B-field — defaults",
    inputs: {},
    fields: ["magneticField", "inductance", "storedEnergy"],
    tolerancePercent: 10,
    source: "Advanced systems calculator defaults",
  },
  {
    id: "superconducting-systems-indicative-01",
    moduleId: "superconducting-systems",
    description: "SC magnet margin — defaults",
    inputs: {},
    fields: ["storedEnergy", "currentMargin"],
    tolerancePercent: 10,
    source: "Advanced systems calculator defaults",
  },
  {
    id: "thermal-management-indicative-01",
    moduleId: "thermal-management",
    description: "Thermal network — defaults",
    inputs: {},
    fields: ["totalCapacity", "thermalResistance"],
    tolerancePercent: 10,
    source: "Advanced systems calculator defaults",
  },
  {
    id: "battery-ev-systems-indicative-01",
    moduleId: "battery-ev-systems",
    description: "EV pack sizing — defaults",
    inputs: {},
    fields: ["packVoltage", "packEnergy"],
    tolerancePercent: 10,
    source: "Advanced systems calculator defaults",
  },
  {
    id: "hydrogen-systems-indicative-01",
    moduleId: "hydrogen-systems",
    description: "H2 storage screening — defaults",
    inputs: {},
    fields: ["storedMass", "hoopStress"],
    tolerancePercent: 10,
    source: "Advanced systems calculator defaults",
  },
  {
    id: "precision-motion-indicative-01",
    moduleId: "precision-motion",
    description: "Stage stiffness — defaults",
    inputs: {},
    fields: ["stiffness", "naturalFrequency"],
    tolerancePercent: 10,
    source: "Advanced systems calculator defaults",
  },
  {
    id: "unit-converter-indicative-01",
    moduleId: "unit-converter",
    description: "MPa to psi conversion",
    inputs: { value: 100, fromUnit: "MPa", toUnit: "psi", dimension: "stress" },
    fields: ["convertedValue"],
    tolerancePercent: 1,
    source: "Unit conversion",
  },
  {
    id: "unit-converter-indicative-02",
    moduleId: "unit-converter",
    description: "mm to in conversion",
    inputs: { value: 25.4, fromUnit: "mm", toUnit: "in", dimension: "length" },
    fields: ["convertedValue"],
    tolerancePercent: 0.1,
    source: "Unit conversion",
  },
  {
    id: "unit-converter-indicative-03",
    moduleId: "unit-converter",
    description: "C to F temperature conversion",
    inputs: { value: 20, fromUnit: "C", toUnit: "F", dimension: "temperature" },
    fields: ["convertedValue"],
    tolerancePercent: 0.1,
    source: "Unit conversion",
  },
];
