export const REPORT_PRODUCT_NAME = "PhyCalcPro";
export const REPORT_TAGLINE = "Engineering calculation workspace";
export const REPORT_SUPPORT_EMAIL = "support@phycalcpro.com";

export function getReportSiteUrl(): string {
  const url = process.env.NEXT_PUBLIC_APP_URL?.trim();
  if (url) return url.replace(/\/+$/, "");
  return "https://www.phycalcpro.com";
}

export const REPORT_DISCLAIMER =
  "This report is generated by PhyCalcPro for design-assist purposes. " +
  "Results are indicative unless validated against applicable standards and project requirements. " +
  "Do not rely on this report as the sole basis for design decisions.";

export function formatReportGeneratedAt(date = new Date()): {
  local: string;
  utc: string;
  isoDate: string;
} {
  const isoDate = date.toISOString().slice(0, 10);
  const utc = date.toISOString().replace("T", " ").slice(0, 16) + " UTC";
  const local = date.toLocaleString(undefined, {
    year: "numeric",
    month: "short",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
  return { local, utc, isoDate };
}

export function formatReportFooterLeft(siteUrl = getReportSiteUrl()): string {
  return `${REPORT_PRODUCT_NAME} · ${siteUrl} · Design-assist calculation report`;
}

export function formatReportFooterRight(page: number, totalPages: number, date = new Date()): string {
  const { local } = formatReportGeneratedAt(date);
  return `Page ${page} of ${totalPages} · Generated ${local}`;
}
