// Auto-generated by scripts/sync-equation-registry.mjs — do not edit by hand.
import type { EquationReference } from "../types";

export const generatedModuleEquations: Record<string, EquationReference[]> = {
  "battery-ev-systems": [
    { id: "eq-1", label: "Equation 1", expression: "V_{\\mathrm{pack}} = N_s V_{\\mathrm{cell}}, \\quad E_{\\mathrm{kWh}} = \\frac{V_{\\mathrm{pack}} N_p C_{\\mathrm{Ah}}}{1000}" },
    { id: "eq-2", label: "Equation 2", expression: "P_{\\mathrm{heat}} = N_s N_p I_{\\mathrm{cell}}^2 R_{\\mathrm{cell}}" },
    { id: "eq-3", label: "Equation 3", expression: "\\dot{m} = \\frac{P_{\\mathrm{heat}}}{c_p \\Delta T}, \\quad A_{\\mathrm{bar}} = \\frac{I}{j_{\\mathrm{allow}}}" },
  ],
  "bevel-gears": [
    { id: "eq-1", label: "Equation 1", expression: "\\delta_1 = \\arctan\\left(\\frac{\\sin\\Sigma}{N_2/N_1 + \\cos\\Sigma}\\right), \\quad \\delta_2 = \\Sigma - \\delta_1" },
    { id: "eq-2", label: "Equation 2", expression: "d_{m1} = m_m N_1, \\quad R_m = \\frac{d_{m1}}{2\\sin\\delta_1}" },
    { id: "eq-3", label: "Equation 3", expression: "\\sigma_F = \\frac{W_t K_A K_V}{b m_m Y} \\leq \\sigma_{FP}, \\quad \\sigma_H \\leq \\sigma_{HP}" },
  ],
  "bolts": [
    { id: "eq-1", label: "Equation 1", expression: "F_b = F_i + \\frac{k_b}{k_b + k_m} F_e" },
    { id: "eq-2", label: "Equation 2", expression: "\\tau_{\\mathrm{thread}} = \\frac{F_{\\mathrm{shear}}}{A_s}, \\quad \\sigma_t = \\frac{F_b}{A_t}" },
    { id: "eq-3", label: "Equation 3", expression: "T = K F_i d, \\quad \\eta_{\\mathrm{screw}} = \\frac{\\tan\\lambda}{\\tan(\\lambda + \\phi)}" },
  ],
  "brakes-clutches": [
    { id: "eq-1", label: "Equation 1", expression: "T = n \\mu F_n r_{\\mathrm{eff}}" },
    { id: "eq-2", label: "Equation 2", expression: "E_{\\mathrm{stop}} = \\frac{1}{2} I \\omega^2 = \\frac{1}{2} I \\left(\\frac{2\\pi n}{60}\\right)^2" },
    { id: "eq-3", label: "Equation 3", expression: "P_{\\mathrm{avg}} = E \\cdot f_{\\mathrm{cycles}}" },
  ],
  "cams": [
    { id: "eq-1", label: "Equation 1", expression: "v = \\omega \\frac{ds}{d\\theta}, \\quad a = \\omega^2 \\frac{d^2 s}{d\\theta^2}" },
    { id: "eq-2", label: "Equation 2", expression: "\\phi = \\arctan\\left(\\frac{ds/d\\theta}{r + s + s_{\\mathrm{offset}}}\\right)" },
    { id: "eq-3", label: "Equation 3", expression: "\\sigma_c = \\sqrt{\\frac{F E^*}{\\pi b \\rho_{\\mathrm{eq}}}}" },
  ],
  "circular-plates": [
    { id: "eq-1", label: "Equation 1", expression: "D \\left( \\frac{d^4 w}{dr^4} + \\frac{2}{r}\\frac{d^3 w}{dr^3} - \\frac{1}{r^2}\\frac{d^2 w}{dr^2} + \\frac{1}{r^3}\\frac{dw}{dr} \\right) = p" },
    { id: "eq-2", label: "Equation 2", expression: "D = \\frac{E t^3}{12(1-\\nu^2)}" },
    { id: "eq-3", label: "Equation 3", expression: "\\sigma_{\\max} = \\frac{\\beta p a^2}{t^2}" },
  ],
  "composites": [
    { id: "eq-1", label: "Equation 1", expression: "\\begin{Bmatrix} \\mathbf{N} \\\\ \\mathbf{M} \\end{Bmatrix} = \\begin{bmatrix} \\mathbf{A} & \\mathbf{B} \\\\ \\mathbf{B} & \\mathbf{D} \\end{bmatrix} \\begin{Bmatrix} \\boldsymbol{\\epsilon}^0 \\\\ \\boldsymbol{\\kappa} \\end{Bmatrix}" },
    { id: "eq-2", label: "Equation 2", expression: "\\mathbf{A} = \\sum_k \\mathbf{Q}_k (z_{k+1} - z_k)" },
    { id: "eq-3", label: "Equation 3", expression: "F_{\\mathrm{Tsai-Hill}} = \\frac{\\sigma_1^2}{X^2} - \\frac{\\sigma_1 \\sigma_2}{X^2} + \\frac{\\sigma_2^2}{Y^2} + \\frac{\\tau_{12}^2}{S^2} \\leq 1" },
  ],
  "compression-springs": [
    { id: "eq-1", label: "Equation 1", expression: "k = \\frac{G d^4}{8 D^3 n}" },
    { id: "eq-2", label: "Equation 2", expression: "\\tau = K_w \\frac{8 F D}{\\pi d^3} \\leq 0.56 R_m" },
    { id: "eq-3", label: "Equation 3", expression: "f_{\\mathrm{surge}} = \\frac{1}{2}\\sqrt{\\frac{k}{m_{\\mathrm{active}}}}" },
    { id: "eq-4", label: "Equation 4", expression: "\\frac{L_0}{D} \\leq \\frac{2.63}{\\nu} \\quad \\text{(buckling screen)}" },
  ],
  "corrosion": [
    { id: "eq-1", label: "Equation 1", expression: "CA = r \\cdot t_{\\mathrm{design\\_life}}" },
    { id: "eq-2", label: "Equation 2", expression: "t_{\\mathrm{required}} = t_{\\mathrm{pressure}} + CA" },
    { id: "eq-3", label: "Equation 3", expression: "t_{\\mathrm{remaining\\_life}} = \\frac{t_{\\mathrm{now}} - t_{\\mathrm{min}}}{r}" },
  ],
  "cost-estimator": [
    { id: "eq-1", label: "Equation 1", expression: "m = \\rho V, \\quad C_{\\mathrm{material}} = m \\cdot c_{\\mathrm{kg}}" },
    { id: "eq-2", label: "Equation 2", expression: "C_{\\mathrm{process}} = t_{\\mathrm{mach}} r_{\\mathrm{mach}} + t_{\\mathrm{labor}} r_{\\mathrm{labor}}" },
    { id: "eq-3", label: "Equation 3", expression: "C_{\\mathrm{total}} = C_{\\mathrm{material}} + C_{\\mathrm{process}} + C_{\\mathrm{finish}} + C_{\\mathrm{overhead}}" },
  ],
  "cryogenic-engineering": [
    { id: "eq-1", label: "Equation 1", expression: "Q_c = \\frac{k A \\Delta T}{L}, \\quad Q_r = \\varepsilon \\sigma A (T_h^4 - T_c^4)" },
    { id: "eq-2", label: "Equation 2", expression: "\\dot{m}_{\\mathrm{boil}} = \\frac{Q \\cdot 86400}{h_{fg}} \\quad \\text{(kg/day)}" },
    { id: "eq-3", label: "Equation 3", expression: "E_{\\mathrm{cool}} = m c_p \\Delta T, \\quad t_{\\mathrm{cool}} = \\frac{E_{\\mathrm{cool}}}{P_{\\mathrm{cool}}}" },
  ],
  "extension-springs": [
    { id: "eq-1", label: "Equation 1", expression: "F = F_i + k x, \\quad k = \\frac{G d^4}{8 D^3 n}" },
    { id: "eq-2", label: "Equation 2", expression: "\\tau_{\\mathrm{body}} = K_w \\frac{8 (F_i + k x_{\\max}) D}{\\pi d^3}" },
    { id: "eq-3", label: "Equation 3", expression: "SF = \\frac{\\tau_{\\mathrm{allow}}}{\\tau_{\\mathrm{body}}}" },
  ],
  "fatigue": [
    { id: "eq-1", label: "Equation 1", expression: "\\frac{S_a}{S_e} + \\frac{S_m}{S_u} = 1 \\quad \\text{(Modified Goodman)}" },
    { id: "eq-2", label: "Equation 2", expression: "S_e = k_a k_b k_c S_e', \\quad k_a = a S_u^b \\quad \\text{(surface finish)}" },
    { id: "eq-3", label: "Equation 3", expression: "S_f = a N^b, \\quad a = \\frac{(f S_u)^2}{S_e}, \\quad b = -\\frac{\\log_{10}(f S_u / S_e)}{3}" },
  ],
  "fits": [
    { id: "eq-1", label: "Equation 1", expression: "i = 0.45 D^{1/3} + 0.001 D \\quad \\text{(µm, } D \\text{ in mm)}" },
    { id: "eq-2", label: "Equation 2", expression: "IT = i \\times \\mathrm{grade}" },
    { id: "eq-3", label: "Equation 3", expression: "c_{\\min} = (D + ES_{\\min}^{\\mathrm{hole}}) - (D + es_{\\max}^{\\mathrm{shaft}})" },
  ],
  "flywheels": [
    { id: "eq-1", label: "Equation 1", expression: "E = \\frac{1}{2} I \\omega^2, \\quad \\Delta E = \\frac{1}{2} I (\\omega_{\\max}^2 - \\omega_{\\min}^2)" },
    { id: "eq-2", label: "Equation 2", expression: "C_s = \\frac{\\omega_{\\max} - \\omega_{\\min}}{\\omega_{\\mathrm{mean}}}" },
    { id: "eq-3", label: "Equation 3", expression: "\\sigma_{\\mathrm{rim}} = \\rho r^2 \\omega^2" },
  ],
  "formula-reference": [
    { id: "eq-1", label: "Equation 1", expression: "E_k = \\frac{1}{2} m v^2" },
    { id: "eq-2", label: "Equation 2", expression: "F = k x, \\quad \\sigma = \\frac{F}{A}" },
    { id: "eq-3", label: "Equation 3", expression: "P V = n R T" },
  ],
  "frames": [
    { id: "eq-1", label: "Equation 1", expression: "\\begin{bmatrix} \\mathbf{K} \\end{bmatrix} \\{\\mathbf{u}\\} = \\{\\mathbf{F}\\}" },
    { id: "eq-2", label: "Equation 2", expression: "\\sigma_{\\mathrm{member}} = \\frac{N}{A} \\pm \\frac{M c}{I}" },
    { id: "eq-3", label: "Equation 3", expression: "U = \\frac{\\sigma_{\\mathrm{combined}}}{\\sigma_{\\mathrm{allow}}}" },
  ],
  "gear-ratio-design": [
    { id: "eq-1", label: "Equation 1", expression: "i = \\frac{N_g}{N_p}, \\quad \\epsilon = \\frac{|N_g/N_p - i_{\\mathrm{target}}|}{i_{\\mathrm{target}}}" },
    { id: "eq-2", label: "Equation 2", expression: "N_p + N_g \\to \\min \\quad \\text{subject to } \\gcd(N_p, N_g) = 1" },
  ],
  "heat-exchangers": [
    { id: "eq-1", label: "Equation 1", expression: "Q = \\dot{m}_h c_{p,h} (T_{h,in} - T_{h,out}) = \\dot{m}_c c_{p,c} (T_{c,out} - T_{c,in})" },
    { id: "eq-2", label: "Equation 2", expression: "\\Delta T_{\\mathrm{lm,cf}} = \\frac{\\Delta T_1 - \\Delta T_2}{\\ln(\\Delta T_1 / \\Delta T_2)}" },
    { id: "eq-3", label: "Equation 3", expression: "\\frac{1}{U} = \\frac{1}{h_h} + \\frac{t}{k} + \\frac{1}{h_c}, \\quad \\mathrm{NTU} = \\frac{UA}{C_{\\min}}" },
  ],
  "hydraulics": [
    { id: "eq-1", label: "Equation 1", expression: "F_{\\mathrm{extend}} = p \\frac{\\pi D^2}{4}, \\quad F_{\\mathrm{retract}} = p \\frac{\\pi (D^2 - d^2)}{4}" },
    { id: "eq-2", label: "Equation 2", expression: "\\sigma_{\\mathrm{rod}} = \\frac{F_{\\mathrm{compress}}}{A_{\\mathrm{rod}}}, \\quad P_{\\mathrm{cr}} = \\frac{\\pi^2 E I}{L_{\\mathrm{eff}}^2}" },
    { id: "eq-3", label: "Equation 3", expression: "\\sigma_h = \\frac{p D}{2 t_{\\mathrm{wall}}}" },
  ],
  "hydrogen-systems": [
    { id: "eq-1", label: "Equation 1", expression: "m = \\frac{P V M}{R T}" },
    { id: "eq-2", label: "Equation 2", expression: "\\sigma_h = \\frac{P r}{t}" },
    { id: "eq-3", label: "Equation 3", expression: "\\dot{m} = C_d A \\sqrt{2 \\rho \\Delta P}" },
  ],
  "impact": [
    { id: "eq-1", label: "Equation 1", expression: "J = m \\Delta v = F_{\\mathrm{avg}} \\Delta t" },
    { id: "eq-2", label: "Equation 2", expression: "\\sigma_d = \\frac{F_{\\mathrm{avg}}}{A}, \\quad SF = \\frac{\\sigma_y}{\\sigma_d}" },
  ],
  "keys-splines": [
    { id: "eq-1", label: "Equation 1", expression: "F_t = \\frac{2T}{d}" },
    { id: "eq-2", label: "Equation 2", expression: "\\tau_{\\mathrm{key}} = \\frac{F_t}{b L} \\leq \\tau_{\\mathrm{allow}}" },
    { id: "eq-3", label: "Equation 3", expression: "\\sigma_{\\mathrm{bearing}} = \\frac{F_t}{h L} \\leq \\sigma_{\\mathrm{b,allow}}" },
  ],
  "load-case-manager": [
    { id: "eq-1", label: "Equation 1", expression: "R_{\\mathrm{env}} = \\max_{i=1}^{n} \\left| R_i \\right|" },
    { id: "eq-2", label: "Equation 2", expression: "U_{\\mathrm{env}} = \\max_i \\frac{\\sigma_i}{\\sigma_{\\mathrm{allow},i}}" },
    { id: "eq-3", label: "Equation 3", expression: "R_{\\mathrm{combined}} = \\sum_j \\gamma_j R_j \\quad \\text{(linear combination)}" },
  ],
  "magnetic-fields": [
    { id: "eq-1", label: "Equation 1", expression: "B = \\frac{\\mu_0 N I}{L}" },
    { id: "eq-2", label: "Equation 2", expression: "L_{\\mathrm{ind}} = \\frac{\\mu_0 N^2 A}{L}, \\quad E = \\frac{1}{2} L_{\\mathrm{ind}} I^2" },
    { id: "eq-3", label: "Equation 3", expression: "F = B I \\ell, \\quad P_{\\mathrm{coil}} = I^2 R" },
  ],
  "material-db": [
    { id: "eq-1", label: "Equation 1", expression: "G = \\frac{E}{2(1+\\nu)}, \\quad \\sigma = E \\varepsilon" },
    { id: "eq-2", label: "Equation 2", expression: "\\rho_{\\mathrm{weight}} = \\rho \\cdot V \\cdot g" },
  ],
  "multi-pulley": [
    { id: "eq-1", label: "Equation 1", expression: "L = \\sum_i \\ell_{\\mathrm{straight},i} + \\sum_j \\frac{\\theta_j D_j}{2}" },
    { id: "eq-2", label: "Equation 2", expression: "\\theta_j = \\pi - (\\alpha_{\\mathrm{in}} + \\alpha_{\\mathrm{out}})_j" },
    { id: "eq-3", label: "Equation 3", expression: "\\theta_{\\min} = \\min_j \\theta_j" },
  ],
  "pins": [
    { id: "eq-1", label: "Equation 1", expression: "\\tau_{\\mathrm{pin}} = \\frac{F}{n_s A_{\\mathrm{pin}}} \\leq \\tau_{\\mathrm{allow}}" },
    { id: "eq-2", label: "Equation 2", expression: "\\sigma_{\\mathrm{bearing}} = \\frac{F}{d t} \\leq \\sigma_{\\mathrm{b,allow}}" },
    { id: "eq-3", label: "Equation 3", expression: "SF = \\min\\left(\\frac{\\tau_{\\mathrm{allow}}}{\\tau_{\\mathrm{pin}}}, \\frac{\\sigma_{\\mathrm{b,allow}}}{\\sigma_{\\mathrm{bearing}}}\\right)" },
  ],
  "pipes": [
    { id: "eq-1", label: "Equation 1", expression: "\\sigma_h = \\frac{p r}{t}, \\quad \\sigma_l = \\frac{p r}{2t}" },
    { id: "eq-2", label: "Equation 2", expression: "\\sigma_{\\mathrm{sustained}} = \\sqrt{\\sigma_h^2 + \\sigma_l^2 + \\sigma_{\\mathrm{bend}}^2}" },
    { id: "eq-3", label: "Equation 3", expression: "\\sigma_{\\mathrm{allow,sustained}} = f \\cdot S_y" },
  ],
  "plain-bearings": [
    { id: "eq-1", label: "Equation 1", expression: "S = \\frac{\\mu n}{p}\\left(\\frac{r}{c}\\right)^2, \\quad p = \\frac{W}{2 r L}" },
    { id: "eq-2", label: "Equation 2", expression: "h_{\\min} = c(1 - \\varepsilon)" },
    { id: "eq-3", label: "Equation 3", expression: "P_{\\mathrm{loss}} = \\frac{2\\pi^2 \\mu n^2 r^3 L}{c}" },
  ],
  "planetary-gears": [
    { id: "eq-1", label: "Equation 1", expression: "i = \\frac{N_R}{N_S} + 1 \\quad \\text{(sun input, carrier output, ring fixed)}" },
    { id: "eq-2", label: "Equation 2", expression: "N_R = N_S + 2 N_P" },
  ],
  "plates": [
    { id: "eq-1", label: "Equation 1", expression: "D \\nabla^4 w = p, \\quad D = \\frac{E t^3}{12(1-\\nu^2)}" },
    { id: "eq-2", label: "Equation 2", expression: "\\sigma_x = \\frac{6 M_x}{t^2}, \\quad \\sigma_y = \\frac{6 M_y}{t^2}" },
    { id: "eq-3", label: "Equation 3", expression: "w_{\\max} \\leq w_{\\mathrm{allow}}" },
  ],
  "precision-motion": [
    { id: "eq-1", label: "Equation 1", expression: "k = \\frac{3 E I}{L^3}, \\quad f_n = \\frac{1}{2\\pi}\\sqrt{\\frac{k}{m}}" },
    { id: "eq-2", label: "Equation 2", expression: "\\delta_{\\mathrm{th}} = \\alpha L \\Delta T" },
    { id: "eq-3", label: "Equation 3", expression: "TR = \\sqrt{\\frac{1 + (2\\zeta r)^2}{(1-r^2)^2 + (2\\zeta r)^2}}" },
  ],
  "profiles": [
    { id: "eq-1", label: "Equation 1", expression: "A = \\int dA, \\quad I_x = \\int y^2 dA, \\quad I_{xy} = \\int xy\\, dA" },
    { id: "eq-2", label: "Equation 2", expression: "I_{1,2} = \\frac{I_x + I_y}{2} \\pm \\sqrt{\\left(\\frac{I_x - I_y}{2}\\right)^2 + I_{xy}^2}" },
  ],
  "rivets": [
    { id: "eq-1", label: "Equation 1", expression: "F_{\\mathrm{shear}} = n \\frac{\\pi d^2}{4} \\tau_{\\mathrm{allow}}" },
    { id: "eq-2", label: "Equation 2", expression: "F_{\\mathrm{bearing}} = n d t \\sigma_{\\mathrm{bearing,allow}}" },
    { id: "eq-3", label: "Equation 3", expression: "F_{\\mathrm{tear}} = n \\left(e - \\frac{d}{2}\\right) t \\sigma_{\\mathrm{tensile}}" },
  ],
  "rolled-sections": [
    { id: "eq-1", label: "Equation 1", expression: "\\sigma = \\frac{M}{S_x}, \\quad \\lambda = \\frac{K L}{r_x}" },
    { id: "eq-2", label: "Equation 2", expression: "w = \\rho A g \\quad \\text{(weight per unit length)}" },
  ],
  "roller-chains": [
    { id: "eq-1", label: "Equation 1", expression: "D = \\frac{p}{\\sin(\\pi/N)}, \\quad v = \\frac{\\pi D n}{60}" },
    { id: "eq-2", label: "Equation 2", expression: "F = \\frac{1000 P}{v}, \\quad i = \\frac{N_2}{N_1}" },
    { id: "eq-3", label: "Equation 3", expression: "L = \\frac{p}{2}\\left(2C/p + N_1 + N_2 + f(N_1,N_2,C)\\right)" },
  ],
  "rotation": [
    { id: "eq-1", label: "Equation 1", expression: "T = I \\alpha, \\quad P = T \\omega = \\frac{T n}{9.55} \\quad \\text{(kW, rpm, N·m)}" },
    { id: "eq-2", label: "Equation 2", expression: "E_k = \\frac{1}{2} I \\omega^2, \\quad t_{\\mathrm{accel}} = \\frac{I \\Delta \\omega}{T_{\\mathrm{net}}}" },
  ],
  "safety-factor": [
    { id: "eq-1", label: "Equation 1", expression: "\\sigma_{\\mathrm{vm}} = \\sqrt{\\frac{(\\sigma_x - \\sigma_y)^2 + (\\sigma_y - \\sigma_z)^2 + (\\sigma_z - \\sigma_x)^2 + 6(\\tau_{xy}^2 + \\tau_{yz}^2 + \\tau_{zx}^2)}{2}}" },
    { id: "eq-2", label: "Equation 2", expression: "SF_y = \\frac{\\sigma_y}{\\sigma_{\\mathrm{vm}}}, \\quad SF_u = \\frac{\\sigma_u}{\\sigma_{\\mathrm{vm}}}" },
  ],
  "sections": [
    { id: "eq-1", label: "Equation 1", expression: "A = \\int dA, \\quad I_x = \\int y^2 dA, \\quad S_x = \\frac{I_x}{c_x}" },
    { id: "eq-2", label: "Equation 2", expression: "I = I_c + A d^2 \\quad \\text{(parallel-axis theorem)}" },
    { id: "eq-3", label: "Equation 3", expression: "r_x = \\sqrt{I_x / A}" },
  ],
  "shaft-hubs": [
    { id: "eq-1", label: "Equation 1", expression: "p = \\frac{\\delta}{\\frac{r}{E_h}(1-\\nu_h) + \\frac{r}{E_s}(1-\\nu_s) + \\frac{r^2}{E_h(r_o^2 - r^2)}}" },
    { id: "eq-2", label: "Equation 2", expression: "T_{\\mathrm{max}} = 2 \\pi \\mu p r^2 L" },
    { id: "eq-3", label: "Equation 3", expression: "\\sigma_{\\theta,\\max} = p \\frac{r_o^2 + r^2}{r_o^2 - r^2}" },
  ],
  "shafts": [
    { id: "eq-1", label: "Equation 1", expression: "\\sigma_{\\mathrm{vm}} = \\sqrt{\\sigma^2 + 3\\tau^2}" },
    { id: "eq-2", label: "Equation 2", expression: "SF_{\\mathrm{static}} = \\frac{\\sigma_y}{\\sigma_{\\mathrm{vm,max}}}, \\quad SF_{\\mathrm{cr}} = \\frac{\\omega_{\\mathrm{cr}}}{\\omega_{\\mathrm{operating}}}" },
  ],
  "superconducting-systems": [
    { id: "eq-1", label: "Equation 1", expression: "E = \\frac{1}{2} L I^2" },
    { id: "eq-2", label: "Equation 2", expression: "M_I = \\frac{I_c - I_{\\mathrm{op}}}{I_c}, \\quad M_T = T_c - T_{\\mathrm{op}}" },
    { id: "eq-3", label: "Equation 3", expression: "V_{\\mathrm{dump}} = I R_d, \\quad \\tau = \\frac{L}{R_d}" },
  ],
  "suspension": [
    { id: "eq-1", label: "Equation 1", expression: "F_y = m_s a_y, \\quad M_{\\mathrm{roll}} = F_y \\frac{w}{2}" },
    { id: "eq-2", label: "Equation 2", expression: "\\phi = \\frac{M_{\\mathrm{roll}}}{k_\\phi}, \\quad \\Delta W = \\frac{F_y h}{t}" },
  ],
  "temperature-properties": [
    { id: "eq-1", label: "Equation 1", expression: "\\varepsilon_{\\mathrm{th}} = \\alpha \\Delta T, \\quad \\sigma_{\\mathrm{thermal}} = E \\alpha \\Delta T \\quad \\text{(restrained)}" },
    { id: "eq-2", label: "Equation 2", expression: "\\sigma_{\\mathrm{allow}}(T) = f_T \\cdot \\sigma_{\\mathrm{allow,room}}" },
  ],
  "thermal-management": [
    { id: "eq-1", label: "Equation 1", expression: "Q_c = \\frac{k A \\Delta T}{t}, \\quad Q_{\\mathrm{conv}} = h A \\Delta T" },
    { id: "eq-2", label: "Equation 2", expression: "Q_r = \\varepsilon \\sigma A (T_h^4 - T_{\\mathrm{amb}}^4)" },
    { id: "eq-3", label: "Equation 3", expression: "R_{\\mathrm{th}} = \\frac{\\Delta T}{Q_{\\mathrm{tot}}}, \\quad \\Delta T_{\\mathrm{coolant}} = \\frac{Q_{\\mathrm{tot}}}{\\dot{m} c_p}" },
  ],
  "timing-belts": [
    { id: "eq-1", label: "Equation 1", expression: "D = \\frac{p N}{\\pi}, \\quad v = \\frac{\\pi D n}{60}" },
    { id: "eq-2", label: "Equation 2", expression: "L_{\\mathrm{pitch}} = 2C + \\frac{\\pi(D_1 + D_2)}{2} + \\frac{(D_2 - D_1)^2}{4C}" },
    { id: "eq-3", label: "Equation 3", expression: "P = \\frac{F_t v}{1000}, \\quad i = \\frac{N_2}{N_1}" },
  ],
  "tolerance": [
    { id: "eq-1", label: "Equation 1", expression: "T_{\\mathrm{WC}} = \\sum_{i=1}^{n} |t_i|" },
    { id: "eq-2", label: "Equation 2", expression: "T_{\\mathrm{RSS}} = \\sqrt{\\sum_{i=1}^{n} t_i^2}" },
    { id: "eq-3", label: "Equation 3", expression: "\\mu_{\\mathrm{MC}} = \\frac{1}{N}\\sum_{j=1}^{N} x_j, \\quad \\sigma_{\\mathrm{MC}} = \\sqrt{\\frac{1}{N-1}\\sum (x_j - \\mu)^2}" },
  ],
  "torsion-springs": [
    { id: "eq-1", label: "Equation 1", expression: "k = \\frac{E d^4}{64 D n_a}" },
    { id: "eq-2", label: "Equation 2", expression: "\\sigma_{\\mathrm{coil}} = \\frac{32 M}{\\pi d^3}, \\quad M = F \\cdot r_{\\mathrm{leg}}" },
    { id: "eq-3", label: "Equation 3", expression: "\\theta = \\frac{M_{\\mathrm{total}}}{k}" },
  ],
  "trusses": [
    { id: "eq-1", label: "Equation 1", expression: "\\frac{EA}{L} \\begin{bmatrix} 1 & -1 \\\\ -1 & 1 \\end{bmatrix} \\{\\mathbf{u}\\} = \\{\\mathbf{F}\\}" },
    { id: "eq-2", label: "Equation 2", expression: "\\sigma = \\frac{N}{A}, \\quad U = \\frac{|\\sigma|}{\\sigma_{\\mathrm{allow}}}" },
  ],
  "unit-converter": [
    { id: "eq-1", label: "Equation 1", expression: "Q_{\\mathrm{target}} = Q_{\\mathrm{source}} \\cdot \\frac{u_{\\mathrm{source\\_to\\_base}}}{u_{\\mathrm{target\\_to\\_base}}}" },
  ],
  "v-belts": [
    { id: "eq-1", label: "Equation 1", expression: "L = 2C + \\frac{\\pi(D_1 + D_2)}{2} + \\frac{(D_2 - D_1)^2}{4C}" },
    { id: "eq-2", label: "Equation 2", expression: "\\frac{F_1}{F_2} = e^{\\mu \\theta}, \\quad P = \\frac{(F_1 - F_2)\\, v}{1000}" },
    { id: "eq-3", label: "Equation 3", expression: "i = \\frac{D_2}{D_1}, \\quad n_2 = \\frac{n_1}{i}" },
  ],
  "vacuum-engineering": [
    { id: "eq-1", label: "Equation 1", expression: "t_{\\mathrm{pumpdown}} = \\frac{V}{S} \\ln\\left(\\frac{P_0}{P_f}\\right)" },
    { id: "eq-2", label: "Equation 2", expression: "C_{\\mathrm{mol}} = \\frac{12.1\\, d^3}{L} \\quad \\text{(L/s, cm units)}" },
    { id: "eq-3", label: "Equation 3", expression: "F = \\Delta P \\cdot A, \\quad Q = P_f S" },
  ],
  "vessels": [
    { id: "eq-1", label: "Equation 1", expression: "t = \\frac{p R}{S E - 0.6 p} \\quad \\text{(cylindrical, ASME UG-27)}" },
    { id: "eq-2", label: "Equation 2", expression: "\\sigma_h = \\frac{p r}{t}, \\quad \\sigma_l = \\frac{p r}{2t}" },
    { id: "eq-3", label: "Equation 3", expression: "\\sigma_r = \\frac{p_i r_i^2 - p_o r_o^2}{r_o^2 - r_i^2} - \\frac{(p_i - p_o) r_i^2 r_o^2}{r_o^2 - r_i^2} \\frac{1}{r^2} \\quad \\text{(Lamé)}" },
  ],
  "vibrations": [
    { id: "eq-1", label: "Equation 1", expression: "(\\mathbf{K} - \\omega^2 \\mathbf{M}) \\mathbf{v} = 0" },
    { id: "eq-2", label: "Equation 2", expression: "f_n = \\frac{\\omega_n}{2\\pi}, \\quad f_d = f_n \\sqrt{1 - \\zeta^2}" },
    { id: "eq-3", label: "Equation 3", expression: "SM = \\frac{|f_{\\mathrm{exc}} - f_n|}{f_n}" },
  ],
  "worm-gears": [
    { id: "eq-1", label: "Equation 1", expression: "\\eta = \\frac{\\tan\\lambda}{\\tan(\\lambda + \\phi)} \\quad \\text{(worm driving)}" },
    { id: "eq-2", label: "Equation 2", expression: "v_s = \\frac{v_1}{\\cos\\lambda}, \\quad d_w = \\frac{m N_w}{\\cos\\lambda}" },
  ],
};
