"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import {
  ArrowRight,
  Bot,
  CircleCheck,
  CircleSlash,
  Sparkles,
  TriangleAlert,
  Workflow,
} from "lucide-react";
import { runCopilotSession, type DesignSession } from "@/lib/copilot";

const EXAMPLE_BRIEFS = [
  "Design a shaft for a 5 kW motor running at 1750 rpm with a service factor of 1.5.",
  "Size a V-belt drive for 7.5 kW at 1450 rpm, service factor 1.4.",
  "Select a bearing for a 3 kN radial load at 3000 rpm with 20000 hours life.",
  "Design a simply supported beam spanning 4 m carrying 12 kN.",
  "Size a compression spring for 250 N with a safety factor of 2.",
];

const STATUS_STYLES: Record<string, { icon: typeof CircleCheck; className: string; label: string }> = {
  ok: { icon: CircleCheck, className: "text-emerald-600 dark:text-emerald-400", label: "Sized" },
  skipped: { icon: CircleSlash, className: "text-slate-400", label: "Manual" },
  error: { icon: TriangleAlert, className: "text-amber-600 dark:text-amber-400", label: "Check" },
};

const MATURITY_LABELS: Record<string, string> = {
  "solver-backed": "Solver-backed",
  "catalog-backed": "Catalog-backed",
  workflow: "Workflow",
};

export default function CopilotPage() {
  const [text, setText] = useState("");
  const [session, setSession] = useState<DesignSession | null>(null);

  const run = (brief: string) => {
    const value = brief.trim();
    if (!value) return;
    setText(brief);
    setSession(runCopilotSession(value));
  };

  const tokenSummary = useMemo(() => {
    if (!session) return [];
    return session.brief.tokens;
  }, [session]);

  return (
    <div className="mx-auto max-w-5xl px-4 py-10 sm:px-6 lg:px-8">
      <div className="flex items-center gap-3">
        <span className="inline-flex h-11 w-11 items-center justify-center rounded-2xl bg-gradient-to-br from-indigo-500 to-violet-600 text-white shadow-sm">
          <Bot className="h-6 w-6" />
        </span>
        <div>
          <h1 className="text-2xl font-semibold text-slate-950 dark:text-white">Design Copilot</h1>
          <p className="text-sm text-slate-500 dark:text-slate-400">
            Describe what you want to build. The copilot plans a module chain, sizes each step, and
            threads the results between them.
          </p>
        </div>
      </div>

      <div className="mt-8 rounded-3xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900">
        <label htmlFor="brief" className="text-sm font-medium text-slate-700 dark:text-slate-200">
          Design brief
        </label>
        <textarea
          id="brief"
          value={text}
          onChange={(event) => setText(event.target.value)}
          rows={3}
          placeholder="e.g. Design a shaft for a 5 kW motor running at 1750 rpm with a service factor of 1.5."
          className="mt-2 w-full resize-none rounded-2xl border border-slate-200 bg-slate-50 p-4 text-sm text-slate-900 outline-none transition focus:border-indigo-400 focus:bg-white dark:border-slate-700 dark:bg-slate-950 dark:text-slate-100"
        />
        <div className="mt-3 flex flex-wrap items-center justify-between gap-3">
          <div className="flex flex-wrap gap-2">
            {EXAMPLE_BRIEFS.map((example) => (
              <button
                key={example}
                type="button"
                onClick={() => run(example)}
                className="rounded-full border border-slate-200 px-3 py-1 text-xs text-slate-600 transition hover:border-indigo-300 hover:text-indigo-600 dark:border-slate-700 dark:text-slate-300 dark:hover:border-indigo-500"
              >
                {example.length > 46 ? `${example.slice(0, 44)}…` : example}
              </button>
            ))}
          </div>
          <button
            type="button"
            onClick={() => run(text)}
            disabled={!text.trim()}
            className="inline-flex items-center gap-2 rounded-2xl bg-indigo-600 px-5 py-2.5 text-sm font-semibold text-white shadow-sm transition hover:bg-indigo-500 disabled:cursor-not-allowed disabled:opacity-50"
          >
            <Sparkles className="h-4 w-4" />
            Plan &amp; size
          </button>
        </div>
      </div>

      {session && (
        <div className="mt-8 space-y-6">
          <BriefSummary session={session} tokens={tokenSummary} />
          <PlanTimeline session={session} />
          <StepResults session={session} />
          <Disclaimer />
        </div>
      )}

      {!session && (
        <p className="mt-6 text-xs text-slate-400">
          Numbers come from PhyCalcPro’s verified module solvers — the copilot only decides which
          modules to run and how to pass parameters between them. Nothing here is generated by a
          language model.
        </p>
      )}
    </div>
  );
}

function BriefSummary({
  session,
  tokens,
}: {
  session: DesignSession;
  tokens: DesignSession["brief"]["tokens"];
}) {
  const { brief } = session;
  return (
    <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900">
      <h2 className="text-sm font-semibold uppercase tracking-wide text-slate-500 dark:text-slate-400">
        Understanding
      </h2>
      <p className="mt-2 text-sm text-slate-700 dark:text-slate-200">{brief.startReason}</p>
      {tokens.length > 0 ? (
        <div className="mt-3 flex flex-wrap gap-2">
          {tokens.map((token, index) => (
            <span
              key={`${token.raw}-${index}`}
              className="rounded-lg bg-slate-100 px-2.5 py-1 text-xs font-medium text-slate-700 dark:bg-slate-800 dark:text-slate-200"
            >
              {token.param}:{" "}
              {token.value >= 1000 || (token.value !== 0 && Math.abs(token.value) < 0.01)
                ? token.value.toExponential(2)
                : token.value}{" "}
              {token.unit}
            </span>
          ))}
        </div>
      ) : (
        <p className="mt-3 text-xs text-slate-400">
          No numeric parameters detected — add values like “5 kW”, “1750 rpm”, or “SF 1.5”.
        </p>
      )}
    </section>
  );
}

function PlanTimeline({ session }: { session: DesignSession }) {
  const { plan } = session;
  return (
    <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900">
      <div className="flex items-center gap-2">
        <Workflow className="h-4 w-4 text-indigo-500" />
        <h2 className="text-sm font-semibold uppercase tracking-wide text-slate-500 dark:text-slate-400">
          Design plan · {plan.steps.length} steps
        </h2>
      </div>
      <div className="mt-4 flex flex-wrap items-center gap-2">
        {plan.steps.map((step, index) => (
          <div key={step.moduleId} className="flex items-center gap-2">
            <Link
              href={step.route}
              className="rounded-xl border border-slate-200 bg-slate-50 px-3 py-1.5 text-sm font-medium text-slate-700 transition hover:border-indigo-300 hover:text-indigo-600 dark:border-slate-700 dark:bg-slate-950 dark:text-slate-200"
            >
              {index + 1}. {step.title}
            </Link>
            {index < plan.steps.length - 1 && <ArrowRight className="h-4 w-4 text-slate-300" />}
          </div>
        ))}
      </div>
      {plan.notes.length > 0 && (
        <ul className="mt-4 space-y-1 text-xs text-slate-500 dark:text-slate-400">
          {plan.notes.map((note) => (
            <li key={note}>• {note}</li>
          ))}
        </ul>
      )}
    </section>
  );
}

function StepResults({ session }: { session: DesignSession }) {
  return (
    <section className="space-y-4">
      {session.results.map((result, index) => {
        const status = STATUS_STYLES[result.status] ?? STATUS_STYLES.ok!;
        const StatusIcon = status.icon;
        return (
          <div
            key={result.step.moduleId}
            className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"
          >
            <div className="flex items-start justify-between gap-4">
              <div>
                <div className="flex items-center gap-2">
                  <span className="text-xs font-semibold text-slate-400">Step {index + 1}</span>
                  <Link
                    href={result.step.route}
                    className="text-base font-semibold text-slate-950 hover:text-indigo-600 dark:text-white"
                  >
                    {result.step.title}
                  </Link>
                  <span className="rounded-full bg-slate-100 px-2 py-0.5 text-[10px] font-medium uppercase tracking-wide text-slate-500 dark:bg-slate-800 dark:text-slate-400">
                    {MATURITY_LABELS[result.step.maturity] ?? result.step.maturity}
                  </span>
                </div>
                <p className="mt-1 text-xs text-slate-500 dark:text-slate-400">{result.step.reason}</p>
              </div>
              <span className={`inline-flex items-center gap-1 text-xs font-medium ${status.className}`}>
                <StatusIcon className="h-4 w-4" />
                {status.label}
              </span>
            </div>

            <p className="mt-3 text-sm text-slate-700 dark:text-slate-200">{result.method}</p>

            {result.recommendation && (
              <div className="mt-3 inline-flex items-center gap-2 rounded-xl bg-indigo-50 px-3 py-1.5 text-sm font-semibold text-indigo-700 dark:bg-indigo-950/50 dark:text-indigo-300">
                {result.recommendation}
                {result.detail && (
                  <span className="text-xs font-normal text-indigo-500 dark:text-indigo-400">
                    · {result.detail}
                  </span>
                )}
              </div>
            )}

            {result.metrics.length > 0 && (
              <div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4">
                {result.metrics.map((metric) => (
                  <div
                    key={metric.label}
                    className="rounded-xl border border-slate-100 bg-slate-50 p-3 dark:border-slate-800 dark:bg-slate-950"
                  >
                    <div className="truncate text-[11px] uppercase tracking-wide text-slate-400">
                      {metric.label}
                    </div>
                    <div className="mt-1 text-sm font-semibold text-slate-900 dark:text-slate-100">
                      {metric.value}
                    </div>
                  </div>
                ))}
              </div>
            )}

            {result.notes.length > 0 && (
              <ul className="mt-4 space-y-1 border-t border-slate-100 pt-3 text-xs text-slate-500 dark:border-slate-800 dark:text-slate-400">
                {result.notes.map((note, noteIndex) => (
                  <li key={noteIndex}>• {note}</li>
                ))}
              </ul>
            )}

            <Link
              href={result.step.route}
              className="mt-4 inline-flex items-center gap-1 text-xs font-medium text-indigo-600 hover:text-indigo-500 dark:text-indigo-400"
            >
              Open {result.step.title} to refine <ArrowRight className="h-3 w-3" />
            </Link>
          </div>
        );
      })}
    </section>
  );
}

function Disclaimer() {
  return (
    <p className="text-xs leading-5 text-slate-400">
      The Design Copilot produces a preliminary, screening-level design. Every value is computed by
      PhyCalcPro’s verified module solvers; the copilot orchestrates the sequence and passes
      parameters between modules. Review each step, confirm assumptions and design-code checks, and
      have results validated by a qualified engineer before use.
    </p>
  );
}
